baseURL = "https://blog.jerryiscat.one/"
title = "Jerry's Blog"
theme = "hugo-blog-awesome"
enableEmoji = true
buildFuture = true
ignoreErrors = ["additional-script-loading-error"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[Languages.zh-cn]
  languageName = "Chinese"
  languageCode = "zh-cn"
  contentDir = "content/zh-cn"
  weight = 1
  hasCJKLanguage = true

  [[Languages.zh-cn.menu.main]]
    pageRef = "/"
    name = "首页"
    url = "/"
    weight = 10
  [[Languages.zh-cn.menu.main]]
    pageRef = "posts"
    name = "文章"
    url = "/posts/"
    weight = 20
  [[Languages.zh-cn.menu.main]]
    pageRef = "about"
    name = "关于"
    url = "/about/"
    weight = 30

  [Languages.zh-cn.params]
    sitename = "Jerry's Blog"
    defaultColor = "auto"
    description = "Jerry 和大橘老师的共创空间"
    mainSections = ["posts"]
    toc = true
    tocOpen = false
    goToTop = true
    dateFormat = "2006-01-02"
    rssFeedDescription = "summary"

    [Languages.zh-cn.params.author]
      name = "Jerry"
      intro = "Jerry's Blog"
      description = "Jerry 和大橘老师的共创空间 🐱"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/jerryisacat"

[[params.socialIcons]]
  name = "Rss"
  url = "/index.xml"

[params.author]
  name = "Jerry"
  email = ""
