baseURL = "https://blog.jerryiscat.one/"
languageCode = "zh-CN"
title = "Jerry's Blog"
theme = "ananke"
defaultContentLanguage = "zh"
hasCJKLanguage = true
enableRobotsTXT = true

[params]
  author = "Jerry"
  description = "Jerry 和大橘老师的共创空间"
  recent_posts_number = 10
