[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.157.0"
  HUGO_ENVIRONMENT = "production"

[[edge_functions]]
  path = "/"
  function = "language-router"

[[edge_functions]]
  path = "/index.html"
  function = "language-router"
